In [1]:
import os

import pandas as pd
import numpy as np

# Start from assignment1 directory
current_dir = os.getcwd().split("/")[-1]
if current_dir != "assignment1":
    os.chdir("..")
current_dir = os.getcwd().split("/")[-1]
assert current_dir=="assignment1", "failed to reach target directory"

In [3]:
"""
Explore diabetes-health-indicators dataset

* Load data
* Count examples
* Evaluate missingness
* Evaluate feature distributions
* Test for skewness and make notes
* Identify target
* Evaluate class balance
* Describe SL problem to solve
* Describe importance and relevance of problem
* Are there additional insights that can be gained from solving similar problem across two datasets?

"""

# Load data
data_path = "data/diabetes_012_health_indicators_BRFSS2015.csv"
df = pd.read_csv(data_path)

In [4]:
df.shape

(253680, 22)

In [6]:
df.columns

Index(['Diabetes_012', 'HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker',
       'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='object')

In [5]:
df.head()

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0